---
- name: Install mackerel-agent (Amazon)
  ansible.builtin.shell: |-
    curl -fsSL https://mackerel.io/file/script/amznlinux/setup-all-yum-v2.sh | MACKEREL_APIKEY='{{ mackerel_apikey }}' sh
  when: ansible_facts.distribution == "Amazon"