---
- name: Install mackerel-agent (Amazon)
  ansible.builtin.shell: |-
    curl -fsSL https://mackerel.io/file/script/amznlinux/setup-all-yum-v2.sh | MACKEREL_APIKEY='{{ mackerel_apikey }}' sh
  when: ansible_facts.distribution == "Amazon"

- name: Install mackerel-agent (Ubuntu)
  ansible.builtin.shell: |-
    wget -q -O - https://mackerel.io/file/script/setup-all-apt-v2.sh | MACKEREL_APIKEY='{{ mackerel_apikey }}' sh
  when: ansible_facts.distribution == "Ubuntu"

- name: Enable and start mackerel-agent
  ansible.builtin.systemd_service:
    name: mackerel-agent.service
    state: started
    enabled: true