---
- name: Install Docker (Amazon)
  ansible.builtin.dnf:
    name: docker
    state: latest
  when: ansible_facts.distribution == "Amazon"

- name: Install Docker (Ubuntu)
  ansible.builtin.shell: |-
    curl -L get.docker.com | bash
  when: ansible_facts.distribution == "Ubuntu"

- name: Enable and start Docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: started
    enabled: true