---
- name: Mkdir /opt/docker/redmine
  ansible.builtin.file:
    path: /opt/docker/redmine
    state: directory
    owner: root
    group: root
    mode: "700"

- name: Add compose.yaml
  ansible.builtin.template:
    src: compose.yaml.jinja
    dest: /opt/docker/redmine/compose.yaml
    owner: root
    group: root
    mode: "600"

- name: Update Redmine
  # community.docker.docker_compose:
  #   project_src: /opt/docker/redmine
  ansible.builtin.shell:
    cmd: docker compose pull
    chdir: /opt/docker/redmine

- name: Destroy Redmine
  # community.docker.docker_compose:
  #   project_src: /opt/docker/redmine
  ansible.builtin.shell:
    cmd: docker compose down -v
    chdir: /opt/docker/redmine

- name: Start Redmine
  # community.docker.docker_compose:
  #   project_src: /opt/docker/redmine
  ansible.builtin.shell:
    cmd: docker compose up -d
    chdir: /opt/docker/redmine

- name: Install build dependencies
  ansible.builtin.shell:
    cmd: docker compose exec redmine /bin/bash -c 'apt update; apt install -y build-essential'
    chdir: /opt/docker/redmine

- name: S3 plugin | Clone
  ansible.builtin.git:
    repo: "https://github.com/redmica/redmica_s3.git"
    dest: /data/redmine/plugins/redmica_s3
    force: true

- name: S3 plugin | Add s3.yml
  ansible.builtin.template:
    src: s3.yml.jinja
    dest: /data/redmine/plugins/redmica_s3/config/s3.yml
    owner: root
    group: root
    mode: "664"

- name: S3 plugin | Patch Gemfile
  ansible.builtin.lineinfile:
    dest: /data/redmine/plugins/redmica_s3/Gemfile
    insertbefore: "BOF"
    regexp: '^source "https://rubygems.org"$'
    line: 'source "https://rubygems.org"'

- name: S3 plugin | Init
  ansible.builtin.shell:
    cmd: |-
      docker compose exec redmine /bin/bash -c 'cd /usr/src/redmine/plugins/redmica_s3; bundle install'
      docker compose cp /data/redmine/plugins/redmica_s3/config/s3.yml redmine:/usr/src/redmine/config/s3.yml
    chdir: /opt/docker/redmine

- name: View customize plugin | Clone
  ansible.builtin.git:
    repo: "https://github.com/onozaty/redmine-view-customize.git"
    dest: /data/redmine/plugins/view_customize
    force: true

- name: View customize plugin | Patch Gemfile
  ansible.builtin.lineinfile:
    dest: /data/redmine/plugins/view_customize/Gemfile
    insertbefore: "BOF"
    regexp: '^source "https://rubygems.org"$'
    line: 'source "https://rubygems.org"'

- name: View customize plugin | Init
  ansible.builtin.shell:
    cmd: docker compose exec redmine /bin/bash -c 'cd /usr/src/redmine/plugins/view_customize; bundle install'
    chdir: /opt/docker/redmine

- name: AI helper plugin | Clone
  ansible.builtin.git:
    repo: "https://github.com/haru/redmine_ai_helper.git"
    dest: /data/redmine/plugins/redmine_ai_helper
    force: true

- name: AI helper plugin | Init
  ansible.builtin.shell:
    cmd: |-
      docker compose exec redmine /bin/bash -c 'cd /usr/src/redmine/plugins/redmine_ai_helper; bundle install'
      docker compose exec redmine /bin/bash -c 'cd /usr/src/redmine; bundle exec rake redmine:plugins:migrate RAILS_ENV=production'
    chdir: /opt/docker/redmine

- name: bleuclair theme | Clone
  ansible.builtin.git:
    repo: "https://github.com/farend/redmine_theme_farend_bleuclair.git"
    dest: /data/redmine/public/themes/bleuclair
    force: true

- name: Restart Redmine
  # community.docker.docker_compose:
  #   project_src: /opt/docker/redmine
  ansible.builtin.shell:
    cmd: docker compose restart redmine
    chdir: /opt/docker/redmine